apiVersion: v1
kind: Secret
metadata:
  name: task-api-secrets
  namespace: task-manager
type: Opaque
stringData:
  DATABASE_URL: "postgres://user:password@postgres.example.com:5432/task_manager?sslmode=require"
  REDIS_URL: "redis://redis.example.com:6379/0"
  JWT_SECRET: "replace-with-a-random-secret-at-least-32-characters"
  NOTIFICATION_PROVIDER_TOKEN: ""
