apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: task-worker
  namespace: task-manager
  labels:
    app.kubernetes.io/name: task-worker
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: task-worker
