apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: task-api-secrets
  namespace: task-manager
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: production-secret-store
    kind: ClusterSecretStore
  target:
    name: task-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: task-manager/production/database-url
    - secretKey: REDIS_URL
      remoteRef:
        key: task-manager/production/redis-url
    - secretKey: JWT_SECRET
      remoteRef:
        key: task-manager/production/jwt-secret
