apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
images:
  - name: task-api
    newName: ghcr.io/cyberyugun/simple-task-manager-api-golang
    newTag: latest
