apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-manager-staging
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - servicemonitor.yaml
patches:
  - path: namespace-delete.yaml
  - path: configmap.yaml
  - path: deployment-patch.yaml
  - path: worker-deployment-patch.yaml
  - path: hpa-patch.yaml
images:
  - name: task-api
    newName: ghcr.io/cyberyugun/simple-task-manager-api-golang
    newTag: latest
