apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-manager-staging
resources:
  - namespace.yaml
  - ../../base/serviceaccount.yaml
  - configmap.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/hpa.yaml
  - ../../base/pdb.yaml
  - ../../base/networkpolicy.yaml
  - ingress.yaml
  - servicemonitor.yaml
patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml
images:
  - name: task-api
    newName: ghcr.io/cyberyugun/simple-task-manager-api-golang
    newTag: latest
