#!/usr/bin/env sh
set -eu

SPEC="internal/apidocs/openapi.yaml"
VERSION="$(awk '/^  version:/{print $2; exit}' "$SPEC")"
PATH_COUNT="$(grep -Ec '^  /.+:$' "$SPEC")"

mkdir -p generated/sdk/typescript generated/sdk/go generated/sdk/python generated/sdk/java generated/sdk/csharp

cat > generated/sdk/typescript/client.ts <<EOF
// Code generated by scripts/generate-sdks.sh; DO NOT EDIT.
export const OPENAPI_VERSION = "${VERSION}";
export const OPENAPI_PATH_COUNT = ${PATH_COUNT};

export class SimpleTaskManagerClient {
  constructor(private readonly baseUrl: string, private readonly accessToken: string) {}

  async request(path: string, init: RequestInit = {}): Promise<Response> {
    const headers = new Headers(init.headers ?? {});
    headers.set("Authorization", "Bearer " + this.accessToken);
    headers.set("Content-Type", headers.get("Content-Type") ?? "application/json");
    return fetch(this.baseUrl.replace(/\/$/, "") + path, { ...init, headers });
  }
}
EOF

cat > generated/sdk/go/client.go <<EOF
// Code generated by scripts/generate-sdks.sh; DO NOT EDIT.
package sdk

import (
	"context"
	"fmt"
	"net/http"
	"strings"
)

const OpenAPIVersion = "${VERSION}"
const OpenAPIPathCount = ${PATH_COUNT}

type Client struct {
	BaseURL     string
	AccessToken string
	HTTPClient  *http.Client
}

func (c Client) NewRequest(ctx context.Context, method, path string) (*http.Request, error) {
	if c.HTTPClient == nil {
		c.HTTPClient = http.DefaultClient
	}
	req, err := http.NewRequestWithContext(ctx, method, strings.TrimRight(c.BaseURL, "/")+path, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+c.AccessToken)
	req.Header.Set("Accept", "application/json")
	return req, nil
}
EOF

cat > generated/sdk/python/client.py <<EOF
# Code generated by scripts/generate-sdks.sh; DO NOT EDIT.
OPENAPI_VERSION = "${VERSION}"
OPENAPI_PATH_COUNT = ${PATH_COUNT}

class SimpleTaskManagerClient:
    def __init__(self, base_url: str, access_token: str):
        self.base_url = base_url.rstrip("/")
        self.access_token = access_token

    def headers(self) -> dict[str, str]:
        return {
            "Authorization": "Bearer " + self.access_token,
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
EOF

cat > generated/sdk/java/Client.java <<EOF
// Code generated by scripts/generate-sdks.sh; DO NOT EDIT.
package generated.sdk;

public final class Client {
    public static final String OPENAPI_VERSION = "${VERSION}";
    public static final int OPENAPI_PATH_COUNT = ${PATH_COUNT};

    private final String baseUrl;
    private final String accessToken;

    public Client(String baseUrl, String accessToken) {
        this.baseUrl = baseUrl.replaceAll("/+$", "");
        this.accessToken = accessToken;
    }

    public String baseUrl() { return baseUrl; }
    public String authorizationHeader() { return "Bearer " + accessToken; }
}
EOF

cat > generated/sdk/csharp/Client.cs <<EOF
// Code generated by scripts/generate-sdks.sh; DO NOT EDIT.
namespace GeneratedSdk;

public sealed class Client
{
    public const string OpenApiVersion = "${VERSION}";
    public const int OpenApiPathCount = ${PATH_COUNT};

    public string BaseUrl { get; }
    public string AccessToken { get; }

    public Client(string baseUrl, string accessToken)
    {
        BaseUrl = baseUrl.TrimEnd('/');
        AccessToken = accessToken;
    }

    public string AuthorizationHeader() => "Bearer " + AccessToken;
}
EOF
